#!/usr/bin/env python3
import os
import re
import subprocess
import filecmp


allTestsPass = True
for filename in sorted(os.listdir()):
    m = re.match('test-in-(.*).rkt', filename)
    if m:
        expectedOutput = 'test-out-'+m.group(1)+'.txt'
        result = subprocess.run('./interpreter',stdin=open(filename),
                                stdout=subprocess.PIPE, stderr=subprocess.PIPE)

        # Get expected output
        with open(expectedOutput,"rb") as expOut:
            expResults = expOut.read()

        testPasses = result.stdout==expResults
        print("Input:",filename,"Expected output:",expectedOutput,
              "Success:",testPasses)

        allTestsPass = allTestsPass and testPasses
        if not testPasses:
            print("Actual output in bytes:")
            print(result.stdout)
            print("Expected output in bytes:")
            print(expResults)

if allTestsPass:
    print('All tests passed!')
else:
    print('At least one test failed.')
